windowrulev2 = float, class:confirmreset
windowrulev2 = float, class:makebranch
windowrulev2 = float, class:maketag
windowrulev2 = float, class:ssh-askpass
windowrulev2 = float, title:branchdialog
windowrulev2 = float, title:pinentry
